name: Example Deployment
on:
  pull_request:
    branches:
      - main
      - master
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    if:
    steps:
    - uses: actions/checkout@v3
    - uses: devopsmakers/pr-name-generator-action@v0.0.1
      id: generator
    - run: echo "Deploying ${{ steps.generator.outputs.name }}"
    - run: echo "${{ github.event }}"
    - name: Comment with link
      #if: ${{ github.event.action == 'opened' || github.event.action == 'reopened' }}
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.number }}
        body: |
          Congratualations! You can access your PR environment at:
            
          https://${{ steps.generator.outputs.name }}.example.com/
        reactions: tada